
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue May 20 21:15:58 CDT 2014
//----------------------------------------------------

package uxmal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 3;
  public static final int DATOS = 13;
  public static final int ABRIRLLA = 9;
  public static final int ENTER = 15;
  public static final int GRAFICA_BARRAS3D = 17;
  public static final int GRAFICA_PASTEL3D = 18;
  public static final int ABRIRPAR = 5;
  public static final int COMA = 2;
  public static final int EOF = 0;
  public static final int VALSTR = 21;
  public static final int CERRARLLA = 10;
  public static final int error = 1;
  public static final int GRAFICA_PASTEL = 16;
  public static final int GRAFICA_LINEAL = 19;
  public static final int CERRARPAR = 6;
  public static final int PCOMA = 4;
  public static final int AGREGAR = 14;
  public static final int FIN = 8;
  public static final int TITULO = 12;
  public static final int COMILLASDOBL = 11;
  public static final int VALINT = 20;
  public static final int INICIO = 7;
}

